[package]
name = "analysis"
version = "0.0.0"
edition = "2021"
authors = ["Luca Lewin <contact@lucalewin.dev>"]
license = "MIT OR Apache-2.0"
tags = ["numerical analysis", "analysis"]

[dependencies]
